### ISSUE TITLE
RxSwift 5.0 support

### ISSUE THREAD

**Issue by trispo** [RxSwiftCommunity/RxSwiftUtilities#18]
Please bump RxSwift dependency to 5.0.

**Comment by farshadtx** [comment]
I have [this PR](https://github.com/RxSwiftCommunity/RxSwiftUtilities/pull/20) open for a while but no luck!

**Comment by nonannoyance** [comment]
Hi there! I'm wondering what the status of this is? Looks like there's a PR that added the support but it's pending updates to the changelog. Any idea when this can be resolved?

**Comment by farshadtx** [comment]
I pushed a new release that has all those commits, can you confirm it works as it expected?

**Comment by nonannoyance** [comment]
Thanks!

Tried installing 2.1.0, but still getting the RxSwift ~4.x dependency requirement.

**Comment by farshadtx** [comment]
Sorry dude, there were a couple of issues with the repo that I fixed in `2.2.0`, but the main blocker is running `trunk push` command.

----
@solidcell @freak4pc , can you trunk push `2.2.0` release?

**Comment by farshadtx** [comment]
@nonannoyance Can you please check it again? V 2.2.0 is out.

**Comment by nonannoyance** [comment]
@farshadtx Yay! I just installed `v2.2.0` with RxSwift ~5.x and no issues. Looks like you're good to go.
